### ISSUE TITLE
Set charge current, not working for me

### ISSUE THREAD

**Issue by Lmhog** [sveinse/zaptec#1]
HI, I'm glad you've picked up on this integration.
I have been able to pause and resume charging for a while, using node red, and it has worked perfectly.
Have missed adjusting the charging voltage :-)

To test it out, I created a script last night with:
service: zaptec.update_installation_1
data:
    installation_id: xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    available_current: 12
Have tried after waiting ½ hour with 16 etc.
What happens is that I get allocated 0 A anyway.
What am I doing wrong :-)

**Comment by sveinse** [comment]
There are a few things to test. First off all, I have deployed a new test version (0.6.0b230722), where the service is improved and renamed to `zaptec.limit_current`. Please test this.

If this doesn't work:
Go into Developer tools -> States and find (or filter) your entity named `sensor.zaptec_installation_*`. There should be four attributes like this: What do they read?

```
available_current: 32
available_current_phase1: 32
available_current_phase2: 32
available_current_phase3: 32
```

**Comment by Lmhog** [comment]
> ensor.zaptec_installation_
Sorry but i'm a newbee in this, but latest bete downloaded from HACS 0.0.6b2, where do i find test version.
And,  right now i'm only have 1 phase, right now, and available_current set to 16A
Is't only work with 3phase?

**Comment by sveinse** [comment]
I'm working on a development version, which you'll find in this repo. In order not to create confusion, I suggest you head over to the main repo https://github.com/custom-components/zaptec and add the question there to show visibility about the problem.

When that is said, the set current function is not currently working in the official version. I do have a development version I'm working on where this is fixes. I must stress that this is an development version and not at all official, so no guarantees. You can go to the readme https://github.com/sveinse/zaptec#readme, and you'll see instructions how to set it up. You MUST uninstall the zaptec version you have installed first.

**Comment by Lmhog** [comment]
Hi thanks for the reply and the development you working on. I would love to test out your versjon, so thank's for your explanation.
As mention's, the official versjon has work fine for me almost a year, but getting the possibility to set current, is a gamechanger. (then I install 32A and 3phase) :-)
