### ISSUE TITLE
Max current per phase

### ISSUE THREAD

**Issue by sumo-89** [sveinse/zaptec#26]
Hi!
I've been using this now and it works awesome, thank you!

I can set:
charger_max_current: 6
charger_min_current: 6

But the charger supports setting this per phase as well. Is it possible to add this to the integration?

**Comment by Gyran** [comment]
You can use the service call `zaptec.limit_current` and specifying `available_current_phase1`, `available_current_phase2` and `available_current_phase3`

**Comment by sumo-89** [comment]
Awesome, now I see it, I thought it was a slider for that as well. But this is perfect! :)

**Comment by sumo-89** [comment]
Closing.
