### ISSUE TITLE
Unknown error when executing Service Set current limit

### ISSUE THREAD

**Issue by Neyn69** [sveinse/zaptec#27]
I'm trying to use the call service Set current limit but will only end up with an error saying: Failed to call service zaptec.limit_current. Unknown Error.
All other services works according to documentation. 
I'm running Home Assistant 2023.9.3.

![image](https://github.com/sveinse/zaptec/assets/121770334/3727c626-21c1-49b8-abd8-78bb808ce083)

**Comment by sveinse** [comment]
I confirm the issue.

**Comment by sveinse** [comment]
Fixed in zaptec-dev 4f9d15a960ed9c1693e22bcaa02acbad7c6f09c0. Please retest.

**Comment by Neyn69** [comment]
Works great now!
Thanks!

![image](https://github.com/sveinse/zaptec/assets/121770334/a481e218-b90e-41fc-93eb-d73ddc9150ac)
