### ISSUE TITLE
Using service limit_current for load balancing, but charger only charge on lowest value.

### ISSUE THREAD

**Issue by blarrkan** [sveinse/zaptec#29]
I´m trying to build a load balancing via node-red and home assistant.

I´m using the function "limit_current", in below I set value for phase 1, phase and phase3. From documentation "available_current" can´t be used when using each phase.

{"installation_id":"ID","available_current_phase1":payload.Phase1,"available_current_phase2":payload.Phase2,"available_current_phase3":payload.Phase3}

If I set phase2 and phase3 to use 13A and phase 1 to use 8A. The value for "available_current" then is set to 8A. So I will never use those 13A on phase2 and phase3.

Any idea how to work this? Is anyone else doing a load balancer? I see several electric companies doing it (Tibber for example).

**Comment by sveinse** [comment]
Hi @blarrkan . I'm not quite sure what's not working here. I tested setting the available current for the phases to 6, 8 and 10 amps. My EV evidently don't want that so it draws 6A on all phases. Zaptec cloud is returning somewhat strange values: It sets "available_current" to 6A, but the read back from Zaptec cloud also shows that the phases are set to 6, 8 and 10 A respectively. So I think this is some behavior of Zaptec cloud.

I've made observations that Tibber adjust the "minChargeCurrent" and "maxChargeCurrent" when their integration is active. Perhaps they use that for load balancing. However, Zaptec docs sais:

_"maxChargeCurrent and minChargeCurrent should in general not be used. These are available for special use cases, where an external party need to override the Zaptec load balancer. Doing this can case unforeseen behavior. It is recommended to control the charging system as a whole using the installations AvailableCurrent settings."_

**Comment by blarrkan** [comment]
Thanks for quick reply. Then it sounds like your getting the same result as me. And as I write, perhaps the EV does not even like or can handle different Amps on each phase. I just saw the possibility with Zaptec.

And the investigation you did with Tibber also sounds like they can´t really load balance (At least have I think load balance should work), as with the feature you mention will limit all phases and not individual phase load balancing.

I guess I have to rethink my load balancing then until perhaps Zaptech cloud can handle different values for each phase. Strange that they have the feature to set different values on each phase, but still sets the avialable_current to the lowest value, that makes no real sence :)

**Comment by sveinse** [comment]
> I guess I have to rethink my load balancing then until perhaps Zaptech cloud can handle different values for each phase. Strange that they have the feature to set different values on each phase, but still sets the avialable_current to the lowest value, that makes no real sence :)

We don't know if this is Zaptec or if its the EV that doesn't support very uneven load. Nor do we know if load balancing is intended to adjust the load between the individual phases. When load balancing is mentioned in zaptec I have the impression it is usually when one has multiple chargers (e.g in a common garage) and the charge current is adjusted dynamically to ensure the circuit doesn't overload.

**Comment by sveinse** [comment]
Can we close this issue? I would like us to move to the official project [custom_components/zaptec ](https://github.com/custom-components/zaptec). Please post any new issue there if the problem still remains (but in this case I'm not sure exactly what to do).
