### ISSUE TITLE
Add more attributes as sensors

### ISSUE THREAD

**Issue by Landcross** [sveinse/zaptec#3]
I just switched from the 'root' HACS addon to this fork to try it out. In the original Zaptec addon, all data was added in the sensor attributes and I added some template sensors to extract those attributes into separate sensors. I noticed that this fork already extracts a bunch of attributes by default. That is great. However, I'm missing some attributes that I used to use from the original Zaptec addon.

I see the attributes are still there in the attributes section of the charger/circuit/installation so I could still use my template sensor, but I think these are nice to add by default nonetheless:

- Charger voltage phase 1
- Charger voltage phase 2
- Charger voltage phase 3
- Charger total change power session
- Humidity
- Signed meter value kwh
- - This one is particularly interesting, because if you set it up correctly with state_class and device_class, you can include the charger power usage in the Home Assistant energy dashboard :)

**Comment by sveinse** [comment]
Thanks for the feedback. Please update to the lasted version. It has all of these with the exception of humidity.

Are humidity more important than temperature to you since temp is not mentioned? There are a handful of temp sensors in there as well.

**Comment by sveinse** [comment]
@Landcross any updates on this issue?

**Comment by Landcross** [comment]
Hey there, my apologies, I was busy and I did read your message but it kinda flew past me 😅

I've updated to the latest version and I can indeed see the new fields. It also seems I can now add the energy usage directly to the energy dashboard (without having to use an intermediary template sensor) so that's great. I haven't yet checked if it's working correctly, but I see no reason why it wouldn't haha.

As for humidity: I thought it would roughly correlate with the outside humidity, thus being a kind of neat little bonus. But I'm not sure if it actually does (roughly) represent the outside humidity as I do not have a proper outside sensor to compare it with. That's also the reason I didn't mention the temperature sensors; because they're all internal temperatures they didn't seem that interesting to me (unless someone is doing some really technical stuff or whatever).

**Comment by sveinse** [comment]
The humidity is to report the humidity inside the device. I think Zaptec uses this to assess if the operating conditions inside the box for their analytics. I would not rely on this sensor for determining outside conditions (although they might be correlated). Remember humidity is highly dependent on temp, and which of the temp sensors report the temp next to the humidity sensor?

I'm not seeing any new requests here, so I'm closing the issue.
