### ISSUE TITLE
Entity Names

### ISSUE THREAD

**Issue by philhumber** [sveinse/zaptec#31]
Perfect install and all functionality appears to work fine. However, entity names are all generic with no ability to see what is what. Icons work fine, but only generic names are displayed. 

E.g button.home; button.home_2; button.home_3

Based on the icons I guessed that these buttons are resume charging, pause charging, and authorise charging. But other entities are almost impossible to figure out. 

The 'friendly' name for all entities under the home device is simply 'home'. For the circuit, the friendly name is always circuit. Same for the entities under the installation device. There is no way to distinguish or understand what each entity does. 

Note: 'home' in this case is the name of my charger set up during the installation.

**Comment by sveinse** [comment]
That is very strange. How does the zaptec entity ID column look like in the Settings -> Devices&Services -> Entities?

**Comment by philhumber** [comment]
![Screenshot_20231111-212742](https://github.com/sveinse/zaptec/assets/95225471/4fd84b04-b67c-4e40-a56f-1e0cec2a5a26)

On mobile - so hopefully this is useful.

**Comment by philhumber** [comment]
Accidentally closed...butter fingers....

**Comment by philhumber** [comment]
Accidentally closed....butter fingers....

**Comment by sveinse** [comment]
Can you post a diagnostics download, please? You'll find a button in one of the Zaptec devices.

**Comment by philhumber** [comment]
No can do. It just doesn't do anything when I try to download through the HA app and it gives me a 'download failed' or 'authorisation needed' error in Chrome if I use the PC. Any other ways to get logs?

**Comment by sveinse** [comment]
This is very strange indeed. I think this is a HA or browser limitation for some unknown reason. I don't have knowledge if there is any ways to trigger diagnostics without UI.

**Comment by sveinse** [comment]
> No can do. It just doesn't do anything when I try to download through the HA app and it gives me a 'download failed' or 'authorisation needed' error in Chrome if I use the PC. Any other ways to get logs?

@philhumber Do you have any errors in the logs that could indicate that the diagnostics function fails?

**Comment by philhumber** [comment]
Great thinking,  an error shows up when clicking download diagnostics. Copy / paste below:

This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/zaptec/diagnostics.py:95
Integration: zaptec-dev (documentation)
First occurred: 14 November 2023 at 21:04:11 (8 occurrences)
Last logged: 01:30:22

Error handling request
Traceback (most recent call last):
  File "/usr/local/share/homeassistant/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/share/homeassistant/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/share/homeassistant/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/local/share/homeassistant/lib/python3.10/site-packages/homeassistant/components/http/security_filter.py", line 67, in security_filter_middleware
    return await handler(request)
  File "/usr/local/share/homeassistant/lib/python3.10/site-packages/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/local/share/homeassistant/lib/python3.10/site-packages/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/local/share/homeassistant/lib/python3.10/site-packages/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/local/share/homeassistant/lib/python3.10/site-packages/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/local/share/homeassistant/lib/python3.10/site-packages/homeassistant/components/diagnostics/__init__.py", line 265, in get
    data = await info.device_diagnostics(hass, config_entry, device)
  File "/home/homeassistant/homeassistant/custom_components/zaptec/diagnostics.py", line 197, in async_get_device_diagnostics
    add(url, data, ctx="state")
  File "/home/homeassistant/homeassistant/custom_components/zaptec/diagnostics.py", line 158, in add
    red.redact_obj_inplace(obj, ctx=ctx)
  File "/home/homeassistant/homeassistant/custom_components/zaptec/diagnostics.py", line 104, in redact_obj_inplace
    self.redact_obj_inplace(k, ctx=ctx, secondpass=secondpass)
  File "/home/homeassistant/homeassistant/custom_components/zaptec/diagnostics.py", line 112, in redact_obj_inplace
    obj[k] = self.redact(
  File "/home/homeassistant/homeassistant/custom_components/zaptec/diagnostics.py", line 95, in redact
    text = text.replace(k, v)
TypeError: replace() argument 1 must be str, not float

**Comment by sveinse** [comment]
Excellent! This is something that have eluded me and should be fixed. I'll start implementing a fix 👌

**Comment by sveinse** [comment]
Tracking the issue for diagnostics gathering in custom-components/zaptec#63.

**Comment by sveinse** [comment]
@philhumber I've released a new 0.7.1b1 that should address the issue of getting the diagnostics file. If you use the official zaptec component from HACS, you'll get this fix if you select the "master" version when installing it. Please install this. It should fix the download diagnostics issue and hopefully we can get some progress with the real issue. Thanks.

**Comment by philhumber** [comment]
Thanks @sveinse. Sorry for the slow reply. I uninstalled fully, and reinstalled the master release of the official component. Download diagnostics is now totally missing. Log extract at the bottom. 

![Screenshot_20231205-235945](https://github.com/sveinse/zaptec/assets/95225471/a8ef5fdf-6316-4cea-b749-c3c692186b13)

This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/zaptec/diagnostics.py:64
Integration: Zaptec EV charger (documentation)
First occurred: 5 December 2023 at 23:23:50 (1 occurrences)
Last logged: 5 December 2023 at 23:23:50

Unexpected exception importing platform custom_components.zaptec.diagnostics
Traceback (most recent call last):
  File "/usr/local/share/homeassistant/lib/python3.10/site-packages/homeassistant/loader.py", line 779, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/local/share/homeassistant/lib/python3.10/site-packages/homeassistant/loader.py", line 796, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/homeassistant/homeassistant/custom_components/zaptec/diagnostics.py", line 28, in <module>
    class Redactor:
  File "/home/homeassistant/homeassistant/custom_components/zaptec/diagnostics.py", line 64, in Redactor
    true,
NameError: name 'true' is not defined

**Comment by sveinse** [comment]
Yes, I'm sorry @philhumber that's on me. There was a bug in master which prevented it to load. I've pushed a fix. Please update and use the latest master (e5fcf16) and try again.

**Comment by philhumber** [comment]
No worries. Here's the log!

[zaptec-5b9d47257b53abea6d619679651f706f-Charge circuit-652f531fd8bd7d6b15bcd7080e9cab28.json](https://github.com/sveinse/zaptec/files/13603690/zaptec-5b9d47257b53abea6d619679651f706f-Charge.circuit-652f531fd8bd7d6b15bcd7080e9cab28.json)

**Comment by sveinse** [comment]
@philhumber I am still puzzled by the data you posted. I've updated the "master" of [custom-components/zaptec](https://github.com/custom-components/zaptec) and I'd like you to install this and rerun the diagnostics download, please. I've added some more logging in order for me to figure out why you get the odd entity names.

I have a hunch that this is related to your entities being named by HA. This is probably due to an old attempt which has set the names for all the entities incorrectly. If you provide a new diagnostics download it will show if this is the case. You could attempt to remove all old entities related to the zaptec integration before installing the new, but I'm not precisely sure how to do that.

**Comment by philhumber** [comment]
We keep trying! Interesting idea on the removing old entries, will try and dig through some system files and see what I can see.

Here's the new logs. Uninstalled Zaptec, restarted instance, installed master zaptec, restarted, added integration, downloaded logs.

[zaptec-63412682519f15a9621bc9b39a3eef03-Charge circuit-652f531fd8bd7d6b15bcd7080e9cab28.json.txt](https://github.com/sveinse/zaptec/files/13794892/zaptec-63412682519f15a9621bc9b39a3eef03-Charge.circuit-652f531fd8bd7d6b15bcd7080e9cab28.json.txt)

**Comment by sveinse** [comment]
I think this is what I suspected, HA is using very strange entity names. An example from your file shows that the entity with unique_id `<--Charger id-->_operating_mode` have received the entity id `switch.home` while in my install the same entity have the entity id `switch.sol_charging`. With other words, the unique_ids are correct, but the entity_id HA assigns them are all weird. My bet would be to try to remote zaptec and then purge the cache for these entities. Though I don't know how, so you might need to google to figure out how. Keep me posted.

This is two example entities in your setup:
```json
        "operating_mode": {
          "entity_id": "switch.home",
          "name": null,
          "unique_id": "<--Charger[91387b]-->_operating_mode"
        },
        "current_phase1": {
          "entity_id": "sensor.home_2",
          "name": null,
          "unique_id": "<--Charger[91387b]-->_current_phase1"
        },
```

In my installation the same data reads (sol is the name of my charger):

```json
        "operating_mode": {
          "entity_id": "switch.sol_charging",
          "name": "Charging",
          "unique_id": "<--Charger[f40861]-->_operating_mode"
        },
        "current_phase1": {
          "entity_id": "sensor.sol_current_phase_1",
          "name": "Current phase 1",
          "unique_id": "<--Charger[f40861]-->_current_phase1"
        },
```

Why the difference, I unfortunately dont know 🤷 . I hope this helps!

**Comment by sveinse** [comment]
Any updates? Can we close this issue (and rather resume any pending issues in the official repo, https://github.com/custom-components/zaptec/issues)?
