### ISSUE TITLE
Add zaptec prefix to auto-created entities

### ISSUE THREAD

**Issue by Landcross** [sveinse/zaptec#4]
I just switched from the 'root' HACS addon to this fork to try it out. In the original Zaptec addon, all data was added in the sensor attributes and I added some template sensors to extract those attributes into separate sensors. I noticed that this fork already extracts a bunch of attributes to entities by default. That is great. However, I noticed that the entity-ids use the installation and charger names as entity-id.

While not necessarily weird or wrong, I would prefer if it would prefix the entity-id with `zaptec_`. Or maybe even `zaptec_charger_`, `zaptec_circuit_` and `zaptec_installation_`

For example, my charger happens to be simply named 'Home' and now I have entities like `sensor.home_current_phase_1` which is super confusing (not to mention that it seems prone to creating duplicate entity-ids).

**Comment by Landcross** [comment]
I ran into it being confusing yet again when I wanted to add your new energy usage attribute (my other issue) to the energy dashboard. Due to my zaptec being called 'Home' the car charger energy usage entity is called `home_energy_meter` which is just ridiculously confusing haha.

I understand that the HA standard is not including component names, but I think in this case you don't necessarily have to view `zaptec` as the component name  but more so the 'object' name (we simply call our charger 'zaptec' here). Instead of `zaptec` it could just as well be `charger` or `wallplug` or whatever.

But yeah, to be fair, part of this issue is just the fact that we named our zaptec kinda awkward, although on the other hand it only becomes awkward by this implementation. In e.g. the zaptec portal itself, the names make sense.

A configurable prefix would indeed be a nice middleground I suppose. I've seen more addons going that route.

Furthermore, a nice optional setting would also be to just ignore the names given by zaptec-api altogether. Zaptec has a lot of features that only really apply when managing bigger installations. I'm just a personal home user and I'm not ever gonna be getting more than 1 charger. It would, for me, be just as good if not better if the custom names were omitted entirely and it'd just be prefix + object type + attribute. So `zaptec_charger_xxx`, `zaptec_circuit_xxx ` and `zaptec_installation_xxx`.

But that 2nd part is maybe too difficult to manage/implement? At the very least a configurable prefix would already go a long way :)

**Comment by sveinse** [comment]
> I ran into it being confusing yet again when I wanted to add your new energy usage attribute (my other issue) to the energy dashboard. Due to my zaptec being called 'Home' the car charger energy usage entity is called `home_energy_meter` which is just ridiculously confusing haha.
>
> I understand that the HA standard is not including component names, but I think in this case you don't necessarily have to view `zaptec` as the component name but more so the 'object' name (we simply call our charger 'zaptec' here). Instead of `zaptec` it could just as well be `charger` or `wallplug` or whatever.

@Landcross You are aware that you can rename entities as you see fit? I think this is how HA intends to customise things like this.

> But yeah, to be fair, part of this issue is just the fact that we named our zaptec kinda awkward, although on the other hand it only becomes awkward by this implementation. In e.g. the zaptec portal itself, the names make sense.
> 
> A configurable prefix would indeed be a nice middleground I suppose. I've seen more addons going that route.

Do you have any examples of integrations that offer this feature? It would be nice to have something to look at for inspiration.

> Furthermore, a nice optional setting would also be to just ignore the names given by zaptec-api altogether. Zaptec has a lot of features that only really apply when managing bigger installations. I'm just a personal home user and I'm not ever gonna be getting more than 1 charger. It would, for me, be just as good if not better if the custom names were omitted entirely and it'd just be prefix + object type + attribute. So `zaptec_charger_xxx`, `zaptec_circuit_xxx ` and `zaptec_installation_xxx`.
> 
> But that 2nd part is maybe too difficult to manage/implement? At the very least a configurable prefix would already go a long way :)

It does require the implementation of a name setting dialog at configuration setup, which will take efforts. What's more complicating, is that different installations have different number of devices, so the UI needs to take this into account. Thus this is something I have to investigate and test how feasible it is to implement.

It can probably be simple to have a button "Ignore device names from Zaptec API" during setup and have it use the legacy `zaptec_charger_xx`, `zaptec_circuit_xx` and `zaptec_installation_xx`. To your opinion, what should `xx` represent here? The very long UUID?

**Comment by Landcross** [comment]
> @Landcross You are aware that you can rename entities as you see fit? I think this is how HA intends to customise things like this.

Yeah, I know and that's great of course. There are probably as many preferences as there are people so we'll probably never get to a solution that _everyone_ agrees with haha. My point was mostly that the current way the entities are named by default can just be quite confusing.

> Do you have any examples of integrations that offer this feature? It would be nice to have something to look at for inspiration.

Some that come to mind are the [SolarEdge Modbus](https://github.com/binsentsu/home-assistant-solaredge-modbus) integration or the [Sleep As Android](https://github.com/IATkachenko/HA-SleepAsAndroid) integration.

> It does require the implementation of a name setting dialog at configuration setup, which will take efforts. What's more complicating, is that different installations have different number of devices, so the UI needs to take this into account. Thus this is something I have to investigate and test how feasible it is to implement.

> It can probably be simple to have a button "Ignore device names from Zaptec API" during setup and have it use the legacy zaptec_charger_xx, zaptec_circuit_xx and zaptec_installation_xx. To your opinion, what should xx represent here? The very long UUID?

Well, in the idea I had in my reply above, the xx part would simply be the specific attribute (e.g. voltage) in case there's only 1 installation/circuit/charger. In case there are more, the given name from zaptec is still perfectly fine. But again, it was just a random idea I had, I'm not sure if it's a good or feasible idea. Just thinking out loud 😅 Going for the 'simpler' solution of just providing an (optional) prefix would already be great imo :)

**Comment by dagstuan** [comment]
I noticed the same thing when switching to this integration. It's really confusing to have entities without a prefix since my charger is called `hjemme`. So I need to either rename my charger, or this integration should somehow let me configure a prefix for the entities :)

**Comment by sveinse** [comment]
I have to be honest that I'm really conflicted about this one. Not that I don't understand and empathize with the need, I do. Adding devices with their names from the remote system (like Zaptec Portal) is precisely how Home Assistant wants it. According to HA devs, it is up to the user to either rename the device in the cloud or in HA itself. So the problem is: Do we follow HA guidelines on this, or do we implement at our own convenience despite HA?

I'm prototyping a configuration option that allows setting a prefix to see how it might look like.

PS! Are you aware that you can rename the devices in Home Assistant and then all the entities under that device will also be renamed? The smallest Zaptec charger installation only have 3 devices in HA (the charger, the circuit and the installation). It's far simpler to rename them than all the entities.

**Comment by dagstuan** [comment]
Ah I wasn't aware of the option to rename the device and then get all entities renamed at the same time. If that name sticks long term then that should fix this issue. So maybe the solution can just be documented then, without changing the integration?

**Comment by sveinse** [comment]
I've added the experimental feature to set the name prefix in build 66fbcd1 which can be downloaded in HACS. How does this fit your wants @dagstuan  and @Landcross ? It's not precisely how HA wants it, but I'm trying it out for size. Happy to hear from you.

**Comment by dagstuan** [comment]
I tried it now @sveinse and it seems to work nicely. However I think that just renaming in HA is even better actually, so I'll go back to doing that. 

Btw it will be really nice when #9 is implemented so I dont have to delete the integration to test 😅
