### ISSUE TITLE
Make Zaptec work in larger installs by selecting which chargers to add

### ISSUE THREAD

**Issue by sveinse** [sveinse/zaptec#5]
If the user has access to many installations and chargers, a huge number of devices and entities will be added to HA. Perhaps it should be a configuration option at configuration that allows to select which devices should be added to HA?

**Comment by sveinse** [comment]
@johnhans I've implemented a new feature in version 66fbcd1 which allows one to select which chargers to add. This should make it very much easier in very large installations. I'm happy to hear from you if you get to test it out.

**Comment by johnhans** [comment]
This works perfectly, logging in using a Zaptec Portal account with access to multiple chargers presents a list of which charges to add to the installation.
